# Generated by Django 4.2.20 on 2025-04-24 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_comments',
            new_name='blog_body',
        ),
    ]
